### ISSUE TITLE
v2ray 启动问题

### ISSUE THREAD

**Issue by kunwu3** [badafans/v2ray-cloudfoundry#1]
按照readme成功部署cf app
运行/app/v2ray/v2ray status 查看运行状态，出现如下信息
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 8080 > v2ray.com/core/transport/internet: failed to
 listen on address: 0.0.0.0:8080 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on0.0.0.0:8080 > listen tcp
 0.0.0.0:8080: bind: address already in use
求教

**Comment by badafans** [comment]
实际v2ray已经在运行了，直接可以通过客户端访问了。具体在容器里面打开SSH 控制界面ps -ef查看进程里面已经有了8080端口运行v2ray

**Comment by badafans** [comment]
> 按照readme成功部署cf app
> 运行/app/v2ray/v2ray status 查看运行状态，出现如下信息
> V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
> A unified platform for anti-censorship.
> Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 8080 > v2ray.com/core/transport/internet: failed to
> listen on address: 0.0.0.0:8080 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on0.0.0.0:8080 > listen tcp
> 0.0.0.0:8080: bind: address already in use
> 求教

实际v2ray已经在运行了，直接可以通过客户端访问了。具体在容器里面打开SSH 控制界面ps -ef查看进程里面已经有了8080端口运行v2ray
