### ISSUE TITLE
VLESS new protocol

### ISSUE THREAD

**Issue by fjweel** [badafans/v2ray-cloudfoundry#15]
大神，可否在4.28.0版出来后，新出一个repository，让cloudfoundry支持VLESS+nginx+ws+tls(可CDN加速)?
Thanks!

**Comment by badafans** [comment]
> 大神，可否在4.28.0版出来后，新出一个repository，让cloudfoundry支持VLESS+nginx+ws+tls(可CDN加速)?
> Thanks!

其实你可以自己替换里面的v2ray文件的

**Comment by fjweel** [comment]
大神你好，v2ctl和v2ray都是单个文件，这两个文件是怎么整出来的？不会弄，原repository里很多文件。

**Comment by fjweel** [comment]
> 大神你好，v2ctl和v2ray都是单个文件，这两个文件是怎么整出来的？不会弄，原repository里很多文件。

从release下载里找到了这两个文件，谢谢！

**Comment by fjweel** [comment]
大神你好，我是小白，VLESS需要over TLS，要申请证书。配置文件中需要提供certificates 和 key file的安装路径。不知cloudfoundry是否可以配置VLESS？
谢谢
