### ISSUE TITLE
请问这种配置方式的v2ray 能通过cloudflare加速么？

### ISSUE THREAD

**Issue by GHinStyle** [badafans/v2ray-cloudfoundry#2]
我按照您的方法 完成了，v2ray的搭建，但是速度实在是太慢了，请问cloudfoundry的容器有通过cloudflare加速的方法么？谢谢！

**Comment by badafans** [comment]
> 我按照您的方法 完成了，v2ray的搭建，但是速度实在是太慢了，请问cloudfoundry的容器有通过cloudflare加速的方法么？谢谢！

请参照cf workers相关设置  https://www.529i.com/archives/772.html

**Comment by GHinStyle** [comment]
我试了一下，真香，感谢！
