### ISSUE TITLE
buildpack

### ISSUE THREAD

**Issue by CSDshumeipai** [badafans/v2ray-cloudfoundry#5]
Downloaded app package (10.1M)
   None of the buildpacks detected a compatible application
   Exit status 222
Error staging application: An app was not successfully detected by any available buildpack

TIP: Use 'cf buildpacks' to see a list of supported buildpacks.
FAILED

**Comment by badafans** [comment]
> Downloaded app package (10.1M)
> None of the buildpacks detected a compatible application
> Exit status 222
> Error staging application: An app was not successfully detected by any available buildpack
> 
> TIP: Use 'cf buildpacks' to see a list of supported buildpacks.
> FAILED

only support golang cloudfoundry
