### ISSUE TITLE
No org targeted, use 'cf target -o ORG' to target an org.

### ISSUE THREAD

**Issue by luxikakashi** [badafans/v2ray-cloudfoundry#7]
No org targeted, use 'cf target -o ORG' to target an org.

**Comment by CSDshumeipai** [comment]
尝试将Cloud Shell location改为Dallas (us-south)

**Comment by luxikakashi** [comment]
破案了，原来我注册账号的时候用的伯力，直接给我注册到欧洲区了，所以怎么都不可以，注册的时候必须是美国，在SHELL的右上角的location记得切换达拉斯，然后就没问题了········
